require:
  - rubocop-rake
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  Exclude:
    - Gemfile
    - 'vendor/**/*'
  NewCops: enable

# Layout

Layout/LineLength:
  Max: 130

Layout/LineEndStringConcatenationIndentation:
  Enabled: false

# Metrics

Metrics/AbcSize:
  Max: 18

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20

# Style

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

# RSpec

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 3

RSpec/NestedGroups:
  Max: 4

RSpec/NoExpectationExample:
  Enabled: false
